# /OruCa/pod.yml

apiVersion: v1
kind: Pod
metadata:
  name: oruca-pod # Pod 全体の名前
  labels:
    project: "fukaya-lab-server" # 管理用の共通ラベル
spec:
  # Pod を fukaya-lab-network に接続する
  networks:
    - name: fukaya-lab-network
      # このネットワークは事前に podman network create で作成しておく

  # Pod として公開するポート (開発用)
  portMappings:
    - containerPort: 4000
      hostPort: 4000
      protocol: tcp

  # Pod 内のコンテナ群
  containers:
    # -----------------------------------------------
    #  OruCa Vite (dev)
    # -----------------------------------------------
    - name: oruca-vite
      image: oruca-vite:latest # (事前に podman build -t oruca-vite ./vite が必要)
      volumeMounts:
        - mountPath: /app
          name: oruca-vite-src
      # 開発時は 4000 ポートを使う
      command: ["tail", "-f", "/dev/null"]
      # (補足) profiles: dev の再現は、dev用の oruca-dev-pod.yml を別途作るのが一般的

    # -----------------------------------------------
    #  OruCa Web (prod)
    # -----------------------------------------------
    - name: oruca-web
      image: oruca-web:latest # (事前に podman build -t oruca-web ./web が必要)
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: oruca-vite-dist
      # caddy がリバースプロキシするポートは 80
      expose:
        - 80
      # caddy-docker-proxy はコンテナのラベルを見る
      labels:
        caddy: http://oruca.fukaya-sus.lab
        caddy.reverse_proxy: "{{upstreams 80}}"
      dependsOn: ["oruca-api"] # Pod内の起動順序制御 (API -> Web)

    # -----------------------------------------------
    #  OruCa API
    # -----------------------------------------------
    - name: oruca-api
      image: oruca-api:latest # (事前に podman build -t oruca-api ./api が必要)
      env:
        # DBへの接続は 'oruca-mysql' ではなく 'localhost' または '127.0.0.1' を使う
        - name: DB_HOST
          value: "127.0.0.1" 
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: oruca-secrets
              key: MYSQL_DATABASE
        # (他の env も同様に secretKeyRef や configMapKeyRef を推奨)
      volumeMounts:
        - mountPath: /app
          name: oruca-api-src
      command: ["yarn", "start"]
      dependsOn: ["oruca-mysql"] # Pod内の起動順序制御 (MySQL -> API)

    # -----------------------------------------------
    #  OruCa MySQL
    # -----------------------------------------------
    - name: oruca-mysql
      image: oruca-mysql:latest # (事前に podman build -t oruca-mysql ./mysql が必要)
      env:
        # (env は secretKeyRef を推奨)
      capAdd:
        - "SYS_NICE"
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: oruca-mysql-init-sql
          subPath: init.sql
        - mountPath: /var/lib/mysql
          name: mysql-data-pvc # PVC をマウント
        - mountPath: /backups
          name: oruca-mysql-backups
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        # (healthcheck の他パラメータもここに記述)

    # -----------------------------------------------
    #  OruCa NFC
    # -----------------------------------------------
    - name: oruca-nfc
      image: oruca-nfc:latest # (事前に podman build -t oruca-nfc ./nfc が必要)
      init: true
      volumeMounts:
        - mountPath: /app
          name: oruca-nfc-src
      env:
        - name: DB_HOST
          value: "127.0.0.1" # API と同様に localhost で接続
        # (他の env)
      command: ["python", "main.py"]
      dependsOn: ["oruca-mysql"] # Pod内の起動順序制御
      # USB デバイスを Pod に渡す設定
      securityContext:
        devices:
          - /dev/bus/usb:/dev/bus/usb

  # Pod が使用するボリュームの定義
  volumes:
    # バインドマウント (hostPath)
    - name: oruca-vite-src
      hostPath:
        path: ./vite
        type: Directory
    - name: oruca-vite-dist
      hostPath:
        path: ./vite/dist
        type: Directory
    - name: oruca-api-src
      hostPath:
        path: ./api
        type: Directory
    - name: oruca-mysql-init-sql
      hostPath:
        path: ./mysql/data/init.sql
        type: File
    - name: oruca-mysql-backups
      hostPath:
        path: ./mysql/backups
        type: Directory
    - name: oruca-nfc-src
      hostPath:
        path: ./nfc
        type: Directory

    # 名前付きボリューム (PersistentVolumeClaim)
    - name: mysql-data-pvc
      persistentVolumeClaim:
        claimName: mysql_data # docker-compose のボリューム名