# /Services/ProjectBotany/justfile

_default:
  @just --list -u

[doc("ProjectBotany サービスに必要な Podman イメージをビルドします。")]
build:
    @echo "==> 🔨 Building ProjectBotany images..."
    @podman build -t botany-vite:latest ./vite
    @echo "==> ✅ ProjectBotany images built."

[doc("ProjectBotany の Pod (pod.yml) を起動します。")]
up: build
    @echo "--> 🚀 Starting ProjectBotany"
    @podman kube play ./pod.yml

[doc("ProjectBotany の Pod (pod.yml) を停止します。")]
down:
    @echo "--> 🛑 Stopping ProjectBotany"
    @podman kube down ./pod.yml