# /Services/ProjectBotany/justfile (修正後)

SERVICE_NAME := shell("basename $(pwd)")

_default:
  @just --list -u

[doc("ProjectBotany サービスに必要な Podman イメージをビルドします。")]
build:
    @echo "🔨 [{{SERVICE_NAME}}] Building images"
    @docker compose --env-file ../../.env build
    @echo "✅ [{{SERVICE_NAME}}] images built"

[doc("ProjectBotany の Pod を起動します。")]
up: build
    @echo "🚀 [{{SERVICE_NAME}}] Starting"
    @docker compose --env-file ../../.env up -d

[doc("ProjectBotany の Pod を停止します。")]
down:
    @echo "🛑 [{{SERVICE_NAME}}] Stopping"
    @docker compose --env-file ../../.env down

[doc("ProjectBotany の PodとVolume を停止します。")]
down-v:
    @echo "🗑️ [{{SERVICE_NAME}}] Stopping pod and deleting volumes..."
    @docker compose down --volumes