# /ProjectBotany/pod.yml (新規作成)

apiVersion: v1
kind: Pod
metadata:
  name: projectbotany-pod
  labels:
    project: "fukaya-lab-server"
spec:
  networks:
    - name: fukaya-lab-network

  containers:
    # -----------------------------------------------
    #  ProjectBotany (dev)
    # -----------------------------------------------
    - name: projectbotany-vite-dev
      image: projectbotany-vite-dev:latest # (事前に podman build -t projectbotany-vite-dev --target dev ./vite が必要)
      volumeMounts:
        - mountPath: /app
          name: projectbotany-vite-src
      expose:
        - 5173
      command: ["yarn", "dev"]
      labels:
        caddy: http://projectbotany.app.fukaya-sus.lab
        caddy.reverse_proxy: "{{upstreams 5173}}"

  volumes:
    # バインドマウント (hostPath)
    - name: projectbotany-vite-src
      hostPath:
        path: ./vite
        type: Directory