# /portainer/pod.yml (新規作成)

apiVersion: v1
kind: Pod
metadata:
  name: portainer-pod
  labels:
    project: "fukaya-lab-server"
spec:
  networks:
    - name: fukaya-lab-network

  containers:
    - name: portainer
      image: portainer/portainer-ce:latest
      expose:
        - 9000
        - 9443
      volumeMounts:
        # Podman のソケットパスに変更
        - mountPath: /var/run/docker.sock
          name: podman-sock
        - mountPath: /data
          name: portainer-data-pvc
      labels:
        caddy: http://portainer.fukaya-sus.lab
        caddy.reverse_proxy: "{{upstreams 9000}}"

  volumes:
    # バインドマウント (hostPath)
    - name: podman-sock
      hostPath:
        path: /var/run/podman/podman.sock # Podman ソケット
        type: Socket
    
    # 名前付きボリューム (PersistentVolumeClaim)
    - name: portainer-data-pvc
      persistentVolumeClaim:
        claimName: portainer_data