# /Services/homepage/justfile (修正後)

_default:
  @just --list -u

[doc("homepage サービスに必要な Podman イメージをビルドします。")]
build:
    @echo "==> 🔨 Building homepage images..."
    @docker compose --env-file ../../.env build
    @echo "==> ✅ homepage images built."

[doc("homepage の Pod (pod.yml) を起動します。")]
up: build
    @echo "--> 🚀 Starting homepage"
    @docker compose --env-file ../../.env up -d

[doc("homepage の Pod (pod.yml) を停止します。")]
down:
    @echo "--> 🛑 Stopping homepage"
    @docker compose --env-file ../../.env 
    
down-v:
    @echo "==> 🗑️ Stopping pod and deleting volumes..."
    @docker compose --env-file ../../.env down --volumes