# /Entry/justfile (修正後)

_default:
  @just --list

# [変更] just Entry::build
build:
    @echo "==> 🔨 Building Entry (if images defined)..."
    @podman compose --env-file ../../.env build

# [変更] just Entry::up
up:
    @echo "--> 🚀 Starting Entry"
    @podman compose --env-file ../../.env up -d

# [変更] just Entry::down
down:
    @echo "--> 🛑 Stopping Entry"
    @podman compose --env-file ../../.env down