# /Entry/justfile

_default:
  @just --list

# [実行例] just Entry::build
build:
    @echo "==> ℹ️ Entry has no images to build."

# [実行例] just Entry::up
up:
    @echo "--> 🚀 Starting Entry"
    @podman kube play ./pod.yml

# [実行例] just Entry::down
down:
    @echo "--> 🛑 Stopping Entry"
    @podman kube down ./pod.yml