# /Entry/pod.yml (新規作成)

apiVersion: v1
kind: Pod
metadata:
  name: entry-pod
  labels:
    project: "fukaya-lab-server"
spec:
  networks:
    - name: fukaya-lab-network
      # AdGuard Home に 172.20.0.11 を割り当て
      podman.io/kube-options: '{"staticIP": ["172.20.0.11"]}'

  portMappings:
    - containerPort: 80
      hostPort: 80
      protocol: tcp
    - containerPort: 443
      hostPort: 443
      protocol: tcp
    # coredns 用のポートマッピング
    - containerPort: 53
      hostPort: 53 # $HOST_IP:$COREDNS_PORT の $HOST_IP 部分は Podman 実行ホストに依存
      protocol: tcp
    - containerPort: 53
      hostPort: 53 # $HOST_IP:$COREDNS_PORT の $HOST_IP 部分は Podman 実行ホストに依存
      protocol: udp

  containers:
    # -----------------------------------------------
    #  Caddy
    # -----------------------------------------------
    - name: entry-caddy
      image: lucaslorentz/caddy-docker-proxy:2.9-alpine
      env:
        - name: CADDY_INGRESS_NETWORKS
          value: "fukaya-lab-network"
      volumeMounts:
        # Podman のソケットパスに変更
        - mountPath: /var/run/docker.sock
          name: podman-sock
        - mountPath: /data
          name: caddy-data-pvc

    # -----------------------------------------------
    #  CoreDNS
    # -----------------------------------------------
    - name: entry-coredns
      image: coredns/coredns:latest
      volumeMounts:
        - mountPath: /Corefile
          name: entry-corefile
      # env: $HOST_IP, $SSH_IP は pod.yml で直接解決できない
      # Corefile を修正するか、ConfigMap を使う必要があります。
      # ここでは localhost (127.0.0.1) または AdGuard (172.20.0.11) を想定
      dependsOn: ["entry-adguardhome"]

    # -----------------------------------------------
    #  AdGuard Home
    # -----------------------------------------------
    - name: entry-adguardhome
      image: adguard/adguardhome:latest
      expose:
        - 3000 # Caddy からのアクセス用
      volumeMounts:
        - mountPath: /opt/adguardhome/work
          name: adguard-work-pvc
        - mountPath: /opt/adguardhome/conf
          name: adguard-conf-pvc
      labels:
        caddy: http://dns.fukaya-sus.lab
        caddy.reverse_proxy: "{{upstreams 3000}}"

  volumes:
    # バインドマウント (hostPath)
    - name: podman-sock
      hostPath:
        path: /var/run/podman/podman.sock # Podman ソケット
        type: Socket
    - name: entry-corefile
      hostPath:
        path: ./Corefile
        type: File

    # 名前付きボリューム (PersistentVolumeClaim)
    - name: caddy-data-pvc
      persistentVolumeClaim:
        claimName: caddy_data
    - name: adguard-work-pvc
      persistentVolumeClaim:
        claimName: adguard_work
    - name: adguard-conf-pvc
      persistentVolumeClaim:
        claimName: adguard_conf